[site]
title = "Arona"
description = "Self-deployment and remote management platform for AI models"

cname = "arona.docs.celestia.world"

[languages]
default = "en"
order = ["en", "zh-Hans", "zh-Hant", "ja", "ko", "fr", "es", "ru", "ar", "de", "pt"]
